import { apiClient } from "@/api/client";

export type Severity = "blocking" | "high" | "medium" | "low";
export interface EvidenceLink { id:string; title:string; url:string; sourceLocation:string; grade:string; relation:string }
export interface Finding { detail:{id:string;area:string;problemType:string;sourceDocument:string;sourceLocation:string;statement:string;finding:string;evidence:EvidenceLink[];reasoningSummary:string;impact:string;requiredAction:string;verificationMethod:string;status:string};severity:Severity;confidence:string }
export interface EvaluationReport { id:string;evaluationId:string;projectId:string;projectName:string;ownerSubject:string;documentId:string;documentName:string;documentVersion:number;country:string;domain:string;targetUser:string;criteriaVersion:string;model:string;verdict:string;confidence:string;conclusion:string;implementationMayStart:boolean;findings:Finding[];areas:{area:string;status:string;reason:string;findingCount:number;confidence:string}[];assumptions:{id:string;statement:string;status:string;dependencies:string[];evidenceIds:string[]}[];contradictions:{id:string;firstLocation:string;firstStatement:string;secondLocation:string;secondStatement:string;reason:string}[];research:{question:string;conclusion:string;sources:EvidenceLink[];conflicts:EvidenceLink[];uncertainties:string[]}[];requiredActions:string[];recommendations:string[];verdictChangeConditions:string[];limitations:string[];summary:{problem:string;purpose:string;targetUser:string;environment:string;solution:string;successCriteria:string};progress:{code:string;label:string;status:string;reason:string}[];evaluationStatus:string }
export interface RevisionResult {report:EvaluationReport;comparison:{id:string;changes:{stableId:string;changeKind:string;reason:string}[];affectedValidationAreas:string[]};reevaluation:{id:string;findings:{findingId:string;status:string;reason:string}[];previousVerdict:string;currentVerdict:string;verdictChanged:boolean;verdictChangeReasons:string[]}}
export interface ImprovementPlan {id:string;evaluationId:string;tasks:{id:string;findingIds:string[];order:number;action:string;requiredResearch:string[];verificationMethod:string;blocking:boolean}[]}
export interface ImprovedPlan {id:string;preservedIntent:string;sections:{key:string;title:string;content:string;sourceFindingIds:string[];evidenceIds:string[]}[];changes:{sectionKey:string;findingIds:string[];before:string;after:string;reason:string}[];unresolvedFindingIds:string[]}
export interface VerdictHistory {documentId:string;changes:{reevaluationId:string;previousEvaluationId:string;currentEvaluationId:string;previousVerdict:string;currentVerdict:string;reasons:string[];criteriaVersion:string;model:string;changedAt:string}[]}
export async function getReport(id:string):Promise<EvaluationReport>{const response=await apiClient.request(`/api/reports/${encodeURIComponent(id)}`);if(!response.ok)throw new Error("리포트를 불러오지 못했습니다.");return response.json() as Promise<EvaluationReport>}
export async function exportReport(id:string,format:"markdown"|"pdf"|"docx"|"json"){const response=await apiClient.request(`/api/reports/${encodeURIComponent(id)}/exports/${format}`);if(!response.ok)throw new Error("내보내기에 실패했습니다.");const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=response.headers.get("content-disposition")?.match(/filename="?([^";]+)"?/)?.[1]??`${id}.${format==="markdown"?"md":format}`;anchor.click();URL.revokeObjectURL(url)}
export async function submitObjection(reportId:string,input:{findingId:string;explanation:string;evidence:{id:string;title:string;urlOrLocation:string;applicableScope:string;contentHash:string}[]}):Promise<{id:string;status:string;researchId:string;verificationStatus:string;remainingUncertainties:string[]}>{const response=await apiClient.request(`/api/reports/${encodeURIComponent(reportId)}/objections`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});if(!response.ok)throw new Error("추가 근거의 원출처를 확인하지 못했거나 이의 제기 접수에 실패했습니다.");return response.json() as Promise<{id:string;status:string;researchId:string;verificationStatus:string;remainingUncertainties:string[]}>}
export async function reviseReport(reportId:string,file:File):Promise<RevisionResult>{const body=new FormData();body.set("file",file);const response=await apiClient.request(`/api/reports/${encodeURIComponent(reportId)}/revisions`,{method:"POST",body});if(!response.ok)throw new Error("수정본 재평가에 실패했습니다.");return response.json() as Promise<RevisionResult>}
export async function createImprovementPlan(reportId:string):Promise<ImprovementPlan>{const response=await apiClient.request(`/api/reports/${encodeURIComponent(reportId)}/improvement-plan`,{method:"POST"});if(!response.ok)throw new Error("보완 계획을 만들지 못했습니다.");return response.json() as Promise<ImprovementPlan>}
export async function improveExistingPlan(reportId:string,input:{originalIntent:string;originalSections:{key:string;title:string;content:string}[];claims:{statement:string;evidenceIds:string[];verified:boolean;findingIds:string[]}[]}):Promise<ImprovedPlan>{const response=await apiClient.request(`/api/reports/${encodeURIComponent(reportId)}/improved-plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});if(!response.ok)throw new Error("검증된 근거로 개선본을 만들지 못했습니다.");return response.json() as Promise<ImprovedPlan>}
export async function getVerdictHistory(reportId:string):Promise<VerdictHistory>{const response=await apiClient.request(`/api/reports/${encodeURIComponent(reportId)}/verdict-history`);if(!response.ok)throw new Error("판정 이력을 불러오지 못했습니다.");return response.json() as Promise<VerdictHistory>}
